config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/dashboard', to: 'dashboard#index'
  delete '/logout', to: 'sessions#destroy'
  resources :users
  resources :history
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/history.rb
class History < ApplicationRecord
  belongs_to :user
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :username, presence: true, uniqueness: true

  belongs_to :role
  has_many :histories
  has_one :point

  def add_point 
    if point.total >= 100 
      point.total = 0
    else 
      point.total += 10
    end
    point.save
  end

  def admin? 
    role_id == 1 ? true : false
  end

  def member?
    role_id == 0 ? true : false 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :current_user?, only: [ :index ]

  def index
  end

  private
  def current_user?
    redirect_to login_path unless signed_in?
  end
end

app/controllers/history_controller.rb
class HistoryController < ApplicationController
  before_action :set_user, only: [:create]
  before_action :set_history, only: [:create]

  def create
    @history.content = "#{DateTime.now.strftime("%d %B %Y")} anda melakukan cukur."
    if @history.save 
      @user.add_point
      redirect_to dashboard_path
    end
  end

  private 
  def set_user 
    @user = User.find_by(id: params[:users])
  end

  def set_history 
    @history = @user.histories.build 
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      sign_in(user)
      redirect_to dashboard_path
    else 
      redirect_to login_path, notice: "Credential is invalid"
    end
  end

  def destroy
    logout
    redirect_to login_path 
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :must_auth, only: [:new, :create]
  before_action :must_admin, only: [:new, :create]
  
  def new 
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save 
      Point.create(user: @user)
      render "confirmation"
    else 
      render 'new'
    end
  end

  private 
  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end

  def must_auth
    redirect_to login_path unless current_user
  end

  def must_admin
    redirect_to login_path unless current_user.admin?
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/history_helper.rb
module HistoryHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user 
    current_user ||= User.find_by(id: session[:user_id])
  end

  def signed_in? 
    current_user.present?
  end

  def logout 
    session.delete(:user_id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/dashboard/index.html.erb
<div class="d-flex justify-content-between align-items-center">
  <div>
    Selamat datang di dashboard <span class="font-weight-bold"><%= current_user.username %></span>. 
  </div>
  <div>
    <%= link_to "Logout", logout_path, method: :delete, class: "btn btn-light btn-sm" %>
  </div>
</div>

<% if current_user.admin? %>
  <div class="my-4 py-4 border-top border-bottom">
    <%= link_to "Pendaftaran User Baru Disini", "/users/new" %>
  </div>
<% end %> 

<% if current_user.admin? %>
  <%= form_with url: history_index_path, method: :post, local: true do |form|  %>
    <div class="d-flex justify-content-between my-4 py-4">
      <div>
        <%= select_tag "users", options_from_collection_for_select(User.all, "id", "username"), class: 'form-control' %>
      </div>
      <div>
        <%= form.submit "Cukur hari ini", class: "btn btn-info btn-xs" %> 
      </div>
    </div>
  <% end  %>
<% end  %>

<% if current_user.member? %>
  <div class="my-4 py-4">
    <div class="my-3">
      Total Point anda: <%= current_user.point.total %>
    </div>
    <div>
      <% if current_user.histories.any? %>
        <ul>
          <% current_user.histories.each do |h| %>
            <li><%= h.content %></li>
          <% end %> 
        </ul>  
      <% else %>
        <p> Maaf, history masih kosong. </p> 
      <% end %> 
    </div>
  </div>
<% end %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HistoryPoints</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container my-4 py-4">
      <div class="col-md-5">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/confirmation.html.erb
<p>Selamat akun anda telah terdaftar, silahkan <%= link_to "Login", "/login" %>.</p>

app/views/users/new.html.erb
<h2 class="my-4">Register New User</h2>

<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |m| %>
        <li><%= m %></li>
      <% end %> 
    </ul>
  </div>
<% end %> 

<%= form_with(model: @user, method: :post, url: users_path, local: true) do |f|  %>
  <div class="form-group row">
    <%= f.label :username, class: 'col-form-label col-md-3' %>
    <div class="col-md-9">
      <%= f.text_field :username, placeholder: :username, class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :password, class: 'col-form-label col-md-3' %>
    <div class="col-md-9">
      <%= f.password_field :password, placeholder: "password", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :password_confirmation, class: 'col-form-label col-md-3' %>
    <div class="col-md-9">
      <%= f.password_field :password_confirmation, placeholder: "password confimation", class: 'form-control' %>
    </div>
  </div>
  <div class="form-group row">
    <div class="col-md-9 offset-md-3">
      <%= f.submit "Register User", class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>